name: Gradle Build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        distribution: 'temurin' # See 'Supported distributions' for available options
        java-version: '17'
    - name: Install Ice
      run: sudo apt-get install zeroc-ice-slice zeroc-ice-compilers
    - name: Build with Gradle
      run: gradle build